services:
  - type: web
    name: python-rewrite-api
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --timeout 120 --workers 1
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
